//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Android_Honeycomb_App1
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_tab_artists = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_tab_artists_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_artists_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int LayoutMain = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int LayoutSecond = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int btnClear = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int btnClickMe = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int btnShowSecond = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int btnTabbedPage = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int screen2Label = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int tvStatus = 2131034117;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Second = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tabbed = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int Yellow = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int btnClear = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int btnClickMe = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textView1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int textView2 = 2130968579;
			
			private String()
			{
			}
		}
	}
}
