//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVISEntities : DbContext
    {
        public MVISEntities()
            : base("name=MVISEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MVIS_MasterSite> MVIS_MasterSite { get; set; }
        public DbSet<MVIS_Section> MVIS_Section { get; set; }
        public DbSet<MVIS_SectionType> MVIS_SectionType { get; set; }
        public DbSet<MVIS_Seller> MVIS_Seller { get; set; }
    }
}
