//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIS_Seller
    {
        public int SellerId { get; set; }
        public int VehicleId { get; set; }
        public string AccountCode { get; set; }
        public string Name { get; set; }
        public string Ad1 { get; set; }
        public string Ad2 { get; set; }
        public string Ad3 { get; set; }
        public string Ad4 { get; set; }
        public string Ad5 { get; set; }
        public string Postcode { get; set; }
        public string TelNo { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
}
