//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIS_Section
    {
        public int SectionID { get; set; }
        public int SectionTypeID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual MVIS_SectionType MVIS_SectionType { get; set; }
    }
}
