//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIS_MasterSite
    {
        public int MasterSiteID { get; set; }
        public string Name { get; set; }
    }
}
