//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVIS_SectionType
    {
        public MVIS_SectionType()
        {
            this.MVIS_Section = new HashSet<MVIS_Section>();
        }
    
        public int SectionTypeID { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MVIS_Section> MVIS_Section { get; set; }
    }
}
